FROM alpine AS builder

ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-aarch64.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM arm64v8/php:fpm-alpine

COPY --from=builder qemu-aarch64-static /usr/bin

RUN rm -f /usr/local/etc/php-fpm.d/*docker.conf

COPY snuffleupagus.sh /opt/snuffleupagus.sh
RUN chmod +x /opt/snuffleupagus.sh && /opt/snuffleupagus.sh

COPY entrypoint.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh
COPY confs/ /opt/confs

VOLUME /www /php-fpm.d /php.d /entrypoint.d

EXPOSE 9000/tcp

ENTRYPOINT ["/opt/entrypoint.sh"]
